'use strict';var Kfa={TAB:0,qm:1,Uq:2},lu=function(){return new qb("MediaRouter.CastStreaming.Session.Launch")},mu=function(){return new wb("MediaRouter.CastStreaming.Session.Length")},nu=function(a){Ab("MediaRouter.CastStreaming.Start.Success",a,Kfa)};var ou=fb("mr.mirror.cast.LogUploader"),qu=function(a,b,c){pu("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?reportid=&q="+encodeURIComponent("UserComments='"+b+"'"):""},pu=function(a,b,c,d){if(0==b.size)ou.info("Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,b);c&&e.append("comments",c);Us("https://clients2.google.com/cr/report",function(f){f=f.target;
var g=null;bt(f)?(g=ct(f),ou.info("Upload to Crash succeeded: "+g)):ou.info("Upload to Crash failed. HTTP status: "+f.cb());d&&d(g)},"POST",e,void 0,3E4)}};var ru=function(){this.g=0;ol(this)},tu=function(){su||(su=new ru);return su},Lfa=function(){var a=tu(),b={fraction:.01,autoSubmitTimeLimitMillis:6048E5},c=b.autoSubmitTimeLimitMillis,d=Date.now();return a.g&&c&&d-a.g<c?!1:Math.random()<b.fraction};ru.prototype.Ka=function(){return"mirror.cast.LogUtils"};ru.prototype.vb=function(){return[void 0,{lastAutoSubmitMillis:this.g}]};ru.prototype.ub=function(){var a=ml(this);this.g=a&&a.lastAutoSubmitMillis||0};var su=null;fb("mr.mirror.cast.LogUtils");var uu={LB:"OFFER",zx:"ANSWER",oC:"PRESENTATION",uz:"GET_STATUS",CD:"STATUS_RESPONSE",sz:"GET_CAPABILITIES",Yx:"CAPABILITIES_RESPONSE",dD:"RPC"};var Mfa=function(){this.capabilities=this.status=this.g=this.error=this.rpc=this.result=this.type=this.h=this.sessionId=null},Ofa=function(a){try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var b;vu(JSON.parse(a),function(d){b=Nfa(d)},function(){throw Error("non-Object result from JSON parse");});return b}catch(d){var c=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(c+". Input was "+a);},Nfa=function(a){var b=new Mfa;null!=a.sessionId&&(b.sessionId=String(a.sessionId));wu(a.seqNum,function(f){b.h=f},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),d=l(Object.keys(uu)),e=d.next();!e.done;e=d.next())if(uu[e.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');b.rpc=new Uint8Array([].concat(n(atob(a.rpc))).map(function(f){return f.charCodeAt(0)}))}vu(a.error,function(f){b.error=Pfa(f)},function(){throw Error('"error" must be an Object');});vu(a.answer,function(f){b.g=Qfa(f)},function(){throw Error('"answer" must be an Object');});vu(a.status,function(f){b.status=Rfa(f)},function(){throw Error('"status" must be an Object');
});vu(a.capabilities,function(f){b.capabilities=Sfa(f)},function(){throw Error('"capabilities" must be an Object');});return b},vu=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},wu=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},xu=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(d){return"number"===typeof d})?b(a):c())},yu=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(d){return String(d)})):c())},Tfa=function(){this.m=null;this.g=[];this.h=
[];this.j=this.l=this.D=null},Qfa=function(a){var b=new Tfa;wu(a.udpPort,function(c){b.m=c},function(){throw Error('"answer.udpPort" must be a number');});xu(a.sendIndexes,function(c){b.g=c},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});xu(a.ssrcs,function(c){b.h=c},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.D=String(a.IV));"receiverGetStatus"in a&&(b.l="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(b.j=
String(a.castMode));return b},Ufa=function(){this.details=this.description=this.code=null},Pfa=function(a){var b=new Ufa;wu(a.code,function(c){b.code=c},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));vu(a.details,function(c){b.details=c},function(){throw Error('"error.details" must be an Object');});return b},Vfa=function(){this.h=this.g=null},Rfa=function(a){var b=new Vfa;wu(a.wifiSnr,function(c){b.g=c},function(){throw Error('"status.wifiSnr" must be a number');
});xu(a.wifiSpeed,function(c){b.h=c},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},Wfa=function(){this.h=this.g=null},Sfa=function(a){var b=new Wfa;yu(a.mediaCaps,function(c){b.g=c},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.h=a.map(function(c){var d;vu(c,function(e){d=Xfa(e)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return d})}return b},Yfa=function(){this.j=this.o=this.D=this.m=this.F=this.g=this.u=this.h=this.initDataTypes=this.l=null},Xfa=function(a){var b=new Yfa;"keySystemName"in a&&(b.l=String(a.keySystemName));yu(a.initDataTypes,function(c){b.initDataTypes=c},function(){throw Error('"capabilities.initDataTypes" must be an array');});yu(a.codecs,function(c){b.h=c},function(){throw Error('"capabilities.codecs" must be an array');});yu(a.secureCodecs,function(c){b.u=c},function(){throw Error('"capabilities.secureCodecs" must be an array');
});yu(a.audioRobustness,function(c){b.g=c},function(){throw Error('"capabilities.audioRobustness" must be an array');});yu(a.videoRobustness,function(c){b.F=c},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.m=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.D=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.o=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(b.j=String(a.distinctiveIdentifierSupport));return b};var zu=function(a){this.s=fb("mr.mirror.cast.MessageDispatcher");this.l=a;this.g=null;this.h=new Map;this.j=0};zu.prototype.subscribe=function(a,b){if(this.h.has(a))throw Error("Attempt to multiple-subscribe to the same response type: "+a);this.h.set(a,b);this.j=0;mb(this.s,"Added subscriber for "+a+"-type messages.");this.g||(this.g=Et(this.l),this.g.onMessage=this.m.bind(this))};
var Au=function(a,b){a.h.delete(b)&&mb(a.s,function(){return"Removed subscriber of "+b+"-type messages."});0==a.h.size&&a.g&&(a.g.jb(),a.g=null)};zu.prototype.sendMessage=function(a){return this.g?"RPC"==a.type?this.g.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.g.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var Bu=function(a,b,c,d,e){var f=null,g=function(){Au(a,c);null!=f&&(clearTimeout(f),f=null)};try{a.subscribe(c,function(k){e(k)&&g()})}catch(k){e(null,k);return}f=setTimeout(function(){g();e(null,Error("timeout"))},d);a.sendMessage(b).catch(function(k){g();e(null,k)})};
zu.prototype.m=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){do{var b=void 0;try{b=Ofa(a.data)}catch(d){b=d.message;break}if(b.type){var c=this.h.get(b.type);if(c)try{c(b);return}catch(d){b="Error thrown during delivery. Response was: "+(JSON.stringify(b)+". Error from subscriber callback was: ")+(d.message+".")}else b="Message was ignored: "+JSON.stringify(b)}else b="Message did not include response type: "+JSON.stringify(b)}while(0);10>
this.j?this.s.L(b):mb(this.s,b);++this.j}};var Cu=function(){this.g=Promise.resolve(1)},Eu=function(a,b,c){return Du(a,function(d){return d==b},c)},Zfa=function(a,b){var c=[3,4];return Du(a,function(d){return-1!=c.indexOf(d)},b)},Fu=function(a,b){a.g=a.g.catch(function(){return 1});return Du(a,function(){return!0},b)},Du=function(a,b,c){var d,e,f=new Promise(function(g,k){d=g;e=k});a.g=a.g.then(function(g){if(!b(g))return e(Error("Operation requires a different starting checkpoint than "+g)),Promise.resolve(g);var k=new $fa(g);try{var m=c(k)}catch(p){m=
Promise.reject(p)}return m.then(function(p){return d(p)},function(p){return e(p)}).then(function(){if(null===k.g)throw Error("A prior operation that started at "+(g+" did not complete."));return k.g})},function(g){e(g);throw g;});return f},$fa=function(a){this.h=a;this.g=null},Gu=function(a,b){a.g="number"===typeof b?b:a.h};var Hu=chrome.cast.streaming,Ju=function(a,b,c,d,e){this.M=a.sessionId;this.F=a.Pg;this.O=a.Ie;this.j=b;this.K=c;this.H=d;this.W=Iu(e,"onAnswer",this.F);this.Xa=Iu(e,"onSessionStop",this.F);this.s=fb("mr.mirror.cast.StreamingLaunchWorkflow");this.C=new Cu;this.o=this.G=this.u=this.h=this.g=this.D=this.m=this.l=null};
Ju.prototype.start=function(a,b,c){var d=this;if(!a&&!b)return Promise.reject(Error("No tracks to stream"));var e=a instanceof Ku,f=b instanceof Ku;(e&&b&&!f||f&&a&&!e)&&Fb("Mixing remoting and non-remoting tracks");return Eu(this.C,1,function(g){d.l=a;d.m=b;d.D=c;d.s.info(function(){return"Launching streaming for "+Lu(d)+" to a "+(d.O+".")});return aga(d).then(d.J.bind(d)).then(function(k){return bga(d,k).then(function(m){d.W();var p=cga(d,m,k);d.g=Mu(d,d.g,p);d.h=Mu(d,d.h,p);if(!d.g&&!d.h)throw Error("Receiver did not select any offers from: "+
JSON.stringify(k));d.G=!!m.l;d.o=function(u,A){u==d.g?d.D.Kf("Audio stream (id="+u+") error: "+A):u==d.h&&d.D.Kf("Video stream (id="+u+") error: "+A)};Hu.rtpStream.onError.addListener(d.o);return dga(d,m,p)})}).then(function(){d.s.info(function(){return"Launched streaming for "+Lu(d)});d.D.kh(d);Gu(g,2);return{ts:d.g,bx:d.h}})})};
Ju.prototype.stop=function(){var a=this;return Fu(this.C,function(b){if(!a.l&&!a.m)return Gu(b,1),Promise.resolve();a.s.info(function(){return"Stopping streaming for "+Lu(a)+"."});a.o&&(Hu.rtpStream.onError.removeListener(a.o),a.o=null);if(a.D){var c=a.D.bi();a.D=null}else c=Promise.resolve();return c.then(function(){a.g&&(Hu.rtpStream.stop(a.g),Hu.rtpStream.destroy(a.g),a.g=null);a.h&&(Hu.rtpStream.stop(a.h),Hu.rtpStream.destroy(a.h),a.h=null);a.u&&(Hu.udpTransport.destroy(a.u),a.u=null);a.Xa();
a.s.info(function(){return"Stopped streaming for "+Lu(a)+"."});a.l=null;a.m=null;Gu(b,1)})})};
var ega=function(a,b){var c=JSON.stringify(b);return Promise.all([a.g&&new Promise(function(d){return Hu.rtpStream.getRawEvents(a.g,c,d)}),a.h&&new Promise(function(d){return Hu.rtpStream.getRawEvents(a.h,c,d)})]).catch(function(d){a.s.error("Unexpected error when calling getRawEvents()",d);return[]}).then(function(d){return new Blob(d.filter(function(e){return!!e}),{type:"application/gzip"})})},fga=function(a){return Promise.all([a.g&&new Promise(function(b){return Hu.rtpStream.getStats(a.g,b)}),
a.h&&new Promise(function(b){return Hu.rtpStream.getStats(a.h,b)})]).catch(function(b){a.s.error("Unexpected error when calling getStats()",b);return[]}).then(function(b){return Object.assign.apply(Object,[{}].concat(n(b.filter(function(c){return!!c}))))})},Lu=function(a){if(a.l&&a.m)var b="audio+video ";else if(a.l)b="audio-only ";else if(a.m)b="video-only ";else return"stopped";return a.l instanceof Ku||a.m instanceof Ku?b+"remoting":b+"streaming"},aga=function(a){return new Promise(function(b){var c=
function(d,e,f){d&&!a.l&&(Hu.rtpStream.destroy(d),d=null);e&&!a.m&&(Hu.rtpStream.destroy(e),e=null);a.s.info(function(){return"Created Cast Streaming session: audioStreamId="+d+", videoStreamId="+e+"."});a.g=d;a.h=e;a.u=f;b()};a.l instanceof Ku||a.m instanceof Ku?Hu.session.create(null,null,c):Hu.session.create(a.l,a.m,c)})};
Ju.prototype.J=function(){for(var a=fj(),b=fj(),c=[],d=l([this.g,this.h]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.g,g=f?127:96,k=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,m=f?48E3:9E4,p=l(Hu.rtpStream.getSupportedParams(e)),u=p.next();!u.done;u=p.next())u=u.value,u.payload.payloadType=g,u.payload.maxLatency=this.j.maxLatencyMillis,u.payload.minLatency=this.j.minLatencyMillis,u.payload.animatedLatency=this.j.animatedLatencyMillis,u.payload.ssrc=
k,u.payload.clockRate=m,u.payload.aesKey=a,u.payload.aesIvMask=b,f?(u.payload.channels=2,u.payload.maxBitrate=this.j.audioBitrate,u.payload.maxFrameRate=100):(u.payload.minBitrate=this.j.minVideoBitrate,u.payload.maxBitrate=this.j.maxVideoBitrate,u.payload.maxFrameRate=this.j.maxFrameRate),c.push(new gga(e,u));return c};
var Mu=function(a,b,c){b&&!c.some(function(d){return d.Sg==b})&&(a.s.L("Destroying RTP stream not selected by the receiver: id="+b),Hu.rtpStream.destroy(b),b=null);return b},bga=function(a,b){return new Promise(function(c,d){for(var e=[],f=0;f<b.length;++f){var g=b[f].params,k={index:f,codecName:g.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:g.payload.payloadType,ssrc:g.payload.ssrc,targetDelay:g.payload.animatedLatency,aesKey:g.payload.aesKey,aesIvMask:g.payload.aesIvMask,timeBase:"1/"+
g.payload.clockRate,receiverRtcpEventLog:a.j.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.j.dscpEnabled&&(k.receiverRtcpDscp=46);127==g.payload.payloadType?Object.assign(k,{type:"audio_source",bitRate:0<g.payload.maxBitrate?1E3*g.payload.maxBitrate:60*g.payload.maxFrameRate+g.payload.clockRate*g.payload.channels,sampleRate:g.payload.clockRate,channels:g.payload.channels}):Object.assign(k,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*g.payload.maxFrameRate)+"/1000",
maxBitRate:1E3*g.payload.maxBitrate,resolutions:[{width:a.j.maxWidth,height:a.j.maxHeight}]});e.push(k)}var m=a.l instanceof Ku||a.m instanceof Ku?"remoting":"mirroring",p={type:"OFFER",sessionId:a.M,seqNum:km(a.K),offer:{castMode:m,receiverGetStatus:!0,supportedStreams:e}};a.s.info(function(){return"Sending OFFER message: "+JSON.stringify(p)});Bu(a.H,p,"ANSWER",1E4,function(u,A){if(null==u)d(A);else if("ok"==u.result&&u.g){if(u.h!=p.seqNum)return a.s.L("Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(u)),!1;((A=u.g.j)&&A!=m||!A&&"mirroring"!=m)&&a.s.error("Expected receiver to ANSWER with castMode="+m+", but got: "+A);mb(a.s,function(){return"Received ANSWER: "+JSON.stringify(u)});c(u.g)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(u)));return!0})})},cga=function(a,b,c){if(b.g.length!=b.h.length)return a.s.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(b)),[];for(var d=[],e={},f=0;f<b.g.length;e={Vf:e.Vf},++f){var g=b.g[f];if(0>g||g>=c.length)return a.s.error("Receiver selected invalid index ("+
g+" < "+c.length+") in ANSWER: "+JSON.stringify(b)),[];e.Vf=c[g];if(d.some(function(k){return function(m){return m.Sg==k.Vf.Sg}}(e)))return a.s.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(b)),[];e.Vf.params.payload.feedbackSsrc=b.h[g];if(d.some(function(k){return function(m){return m.params.payload.feedbackSsrc==k.Vf.params.payload.feedbackSsrc}}(e)))return a.s.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+JSON.stringify(b)),[];d.push(e.Vf)}return d},
dga=function(a,b,c){var d=null,e=function(){d&&(Hu.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(f,g){var k=b.m||2344;a.s.info(function(){return"Starting RTP streams to receiver at "+(a.F+":"+k)+(" for selected offers: "+JSON.stringify(c))});var m=a.u||-1;a.j.dscpEnabled&&(a.s.info("Enabled DSCP in sender."),Hu.udpTransport.setOptions(m,{DSCP:!0}));Hu.udpTransport.setDestination(m,{address:a.F,port:k});var p=new Set(c.map(function(A){return A.Sg}));d=function(A){p.delete(A);
0==p.size&&f()};Hu.rtpStream.onStarted.addListener(d);m=l(c);for(var u=m.next();!u.done;u=m.next())u=u.value,Hu.rtpStream.toggleLogging(u.Sg,a.j.enableLogging),Hu.rtpStream.start(u.Sg,u.params);setTimeout(function(){g(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(f){e();throw f;})},Iu=function(a,b,c){var d=this;return a&&b in a?function(){try{a[b](c)}catch(e){d.s.error("Error from testHooks."+b,e)}}:function(){}},gga=function(a,b){this.Sg=a;this.params=b},Ku=function(){};var Nu=function(a,b,c,d,e,f){this.o=a;this.H=hga(b,this.o.Gb);this.K=new Ju(this.o.Gb,c,d,e,f);this.G=e;this.m=new Cu;this.j=new iga;this.C=new mojo.Binding(mojo.MirrorServiceRemoter,this,null);this.s=fb("mr.mirror.cast.MediaRemoter");this.F=this.g=this.D=this.l=this.J=null;this.h=!0;this.u=this.M.bind(this)};
Nu.prototype.initialize=function(a,b){var c=this;return Eu(this.m,1,function(d){c.J=a;c.l=b;var e=c.C.createInterfacePtrAndBind();c.C.setConnectionErrorHandler(function(){c.s.info("Remoter mojo pipe connection error.");Ou(c)});c.g=new mojo.MirrorServiceRemotingSourcePtr;var f=Naa(c.o.mediaSource||"");if(!f)throw Error("Failed to parse tab ID from source:\n          "+c.o.mediaSource);c.s.info("Connecting remoter to browser: tabId="+f);(ui.get("mr.ProviderManager")||null).onMediaRemoterCreated(f,e,
mojo.makeRequest(c.g));c.g.ptr.setConnectionErrorHandler(function(){c.s.info("RemotingSource mojo pipe connection error.");Ou(c)});return jga(c).then(function(){if(c.h)c.g.onSinkAvailable(c.H);Gu(d,2)})})};
var Ou=function(a){return Fu(a.m,function(b){a.g&&(a.g.ptr.reset(),a.g=null);var c=a.D;a.D=null;a.l=null;a.J=null;a.C.close();chrome.settingsPrivate.onPrefsChanged.hasListener(a.u)&&chrome.settingsPrivate.onPrefsChanged.removeListener(a.u);return new Promise(function(d){window.setTimeout(function(){Pu(a).then(function(){Gu(b,1);d();c&&c()})},250)})})};h=Nu.prototype;h.fw=function(a){Qu(this.j,a)};h.kh=function(a){this.l&&this.l.kh(a)};h.bi=function(){return this.l?this.l.bi():Promise.resolve()};
h.Kf=function(a,b){this.s.error("Error during streaming: "+a,b);if(this.g)this.g.onError();Ou(this)};
h.start=function(){var a=this,b=!1;this.s.info(function(){b=!0;return"Starting next media remoting session."});b&&kga(this.j,function(c){return a.s.info(c)});lga(this.j);Eu(this.m,2,function(c){return(0,a.J)().then(function(d){a.D=d;a.G.subscribe("RPC",function(e){if(e.rpc){var f=a.j;e=e.rpc;f.D&&(++f.o,f.h+=e.length,f.D(e))}});Gu(c,3)}).catch(function(d){return Pu(a).then(function(){Gu(c);throw d;})})}).then(function(){a.s.info("Remoting started successfully.")}).catch(function(c){a.s.error("Failed to start remoting",
c);a.g.onError()})};h.Gw=function(a,b){var c=this;return Eu(this.m,3,function(d){return c.K.start(a?new Ku:null,b?new Ku:null,c).then(function(e){mga(c.j,function(f){return c.G.sendMessage(f)},function(f){c.g.onMessageFromSink(f)});Gu(d,4);return{audio_stream_id:e.ts||-1,video_stream_id:e.bx||-1}}).catch(function(e){return Pu(c).then(function(){Gu(d);throw e;})})}).catch(function(d){c.s.error("Failed to start remoting streams",d);Ou(c);return{audio_stream_id:-1,video_stream_id:-1}})};
h.stop=function(a){var b=this;Zfa(this.m,function(c){b.g.onStopped(a);return Pu(b).then(function(){b.s.info("Remoting stopped.");Gu(c,5);(0,b.D)().then(function(){return Eu(b.m,5,function(d){if(b.g&&b.h)b.g.onSinkAvailable(b.H);Gu(d,2);return Promise.resolve()})}).catch(function(d){throw d;});b.D=null})}).catch(function(c){b.s.error("Failed to stop remoting: ",c);Ou(b)})};
h.Ws=function(){null===this.F&&(this.F=wf(this.o.Gb.Pg).then(function(a){return a.h||!1}));return this.F.then(function(a){return{rate:(a?1E7:5E6)/8}})};
var Pu=function(a){return a.K.stop().then(function(){Au(a.G,"RPC");nga(a.j);Ru(a.j)})},jga=function(a){return new Promise(function(b){chrome.settingsPrivate.getPref("media_router.media_remoting.enabled",function(c){chrome.runtime.lastError?a.s.error("Encountered error getting media remoting pref: "+JSON.stringify(chrome.runtime.lastError)):c.type!=chrome.settingsPrivate.PrefType.BOOLEAN?a.s.error("Pref value not a boolean: "+JSON.stringify(c)):(a.h=!!c.value,a.s.info("Initializing mediaRemotingEnabled_ with value read from pref: "+
a.h));chrome.settingsPrivate.onPrefsChanged.hasListener(a.u)||chrome.settingsPrivate.onPrefsChanged.addListener(a.u);b()})})};
Nu.prototype.M=function(a){if(this.g){a=l(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value,"media_router.media_remoting.enabled"==b.key){if(b.type!=chrome.settingsPrivate.PrefType.BOOLEAN){this.s.error("Pref value not a boolean: "+JSON.stringify(b));break}a=!!b.value;if(this.h==a)break;this.h=a;this.s.info("mediaRemotingEnabled_ changed to: "+this.h);if(this.h)this.g.onSinkAvailable(this.H);else this.g.onStopped(mojo.RemotingStopReason.USER_DISABLED);break}}};
var hga=function(a,b){var c=this,d=new mojo.RemotingSinkMetadata;d.features=[];d.friendly_name=b.Cw||"";d.audio_capabilities=[];d.video_capabilities=[];var e=mojo.RemotingSinkAudioCapability,f=mojo.RemotingSinkVideoCapability,g=d.audio_capabilities,k=d.video_capabilities,m=b.Ie||"";(a.g||[]).forEach(function(p){switch(p){case "audio":g.push(e.CODEC_BASELINE_SET);break;case "aac":g.push(e.CODEC_AAC);break;case "opus":g.push(e.CODEC_OPUS);break;case "video":k.push(f.CODEC_BASELINE_SET);break;case "4k":k.push(f.SUPPORT_4K);
break;case "h264":k.push(f.CODEC_H264);break;case "vp8":k.push(f.CODEC_VP8);break;case "vp9":m.startsWith("Chromecast Ultra")&&k.push(f.CODEC_VP9);break;case "hevc":m.startsWith("Chromecast Ultra")&&k.push(f.CODEC_HEVC);break;default:c.s.info("Unknown mediaCap name: "+p)}});b.Ie&&"Chromecast Ultra"==b.Ie&&k.push(f.SUPPORT_4K);return d};Nu.prototype.estimateTransmissionCapacity=Nu.prototype.Ws;Nu.prototype.stop=Nu.prototype.stop;Nu.prototype.startDataStreams=Nu.prototype.Gw;Nu.prototype.start=Nu.prototype.start;
Nu.prototype.sendMessageToSink=Nu.prototype.fw;
var iga=function(){this.D=this.m=this.g=null;this.F=this.h=this.o=this.j=this.u=0;this.l=null},lga=function(a){a.g=[];Su(a,performance.now())},mga=function(a,b,c){a.m=b;a.D=c;a.g?(b=a.g,a.g=null,b.forEach(function(d){return Qu(a,d.data).then(d.hw,d.sp)})):Su(a,performance.now())},nga=function(a){if(a.g){var b=Error("Stop before delivering pending message");a.g.forEach(function(c){return c.sp(b)});a.g=null}a.m=null;a.D=null},Qu=function(a,b){if(a.m){var c=btoa(String.fromCharCode.apply(null,b));++a.u;
a.j+=b.length;return a.m({type:"RPC",rpc:c})}return a.g?new Promise(function(d,e){a.g.push({data:b,hw:d,sp:e})}):Promise.reject(Error("RPC pipe not started"))},kga=function(a,b){Ru(a);a.l=setInterval(function(){if(a.g)var c=a.g.length+" messages are waiting to send.";else{c=performance.now();var d=(c-a.F)/1E3;d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.u+" messages ("+Math.round(a.j/d)+" bytes/sec) and received ")+(a.o+" messages ("+Math.round(a.h/d)+" bytes/sec).");Su(a,c);c=d}b(c)},3E4)},
Ru=function(a){null!=a.l&&(clearInterval(a.l),a.l=null)},Su=function(a,b){a.u=0;a.j=0;a.o=0;a.h=0;a.F=b};var oga=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},pga=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var Tu=function(a,b,c,d,e){this.j=new Ju(a,b,c,d,void 0===e?null:e);this.s=fb("mr.mirror.cast.MediaStreamer");this.m=new Cu;this.l=this.h=this.g=this.D=null};Tu.prototype.start=function(a,b){var c=this;return Eu(this.m,1,function(d){c.D=a;c.g=oga(a);c.g&&"ended"==c.g.readyState&&(c.g=null);c.h=pga(a);c.h&&"ended"==c.h.readyState&&(c.h=null);if(!c.g&&!c.h)return Gu(d),Promise.reject(Error("No MediaStream tracks to stream."));c.l=b;return c.j.start(c.g,c.h,c.l).then(function(){return Gu(d,2)})})};
Tu.prototype.stop=function(){var a=this;return Fu(this.m,function(b){return a.j.stop().then(function(){a.g=null;a.h=null;a.D=null;a.l=null;Gu(b,1)})})};var qga=function(a){return Eu(a.m,2,function(b){a.s.info("Suspending media streaming...");return a.j.stop().then(function(){a.s.info("Suspended media streaming.");Gu(b,3)})})};
Tu.prototype.resume=function(){var a=this;return Eu(this.m,3,function(b){a.g&&"ended"==a.g.readyState&&(a.g=null);a.h&&"ended"==a.h.readyState&&(a.h=null);if(!a.g&&!a.h)return Promise.reject(Error("Cannot resume: All tracks have ended."));a.s.info("Resuming media streaming...");return a.j.start(a.g,a.h,a.l).then(function(){a.s.info("Resumed media streaming.");Gu(b,2)})})};var Uu=function(a,b,c){this.m=a;this.l=b;this.j=c;this.s=fb("mr.mirror.cast.WifiStatusMonitor");this.g=null;this.h=[]};Uu.prototype.start=function(){var a=this;null==this.g&&(mb(this.s,"Starting Wifi Status Monitoring."),this.h=[],this.j.subscribe("STATUS_RESPONSE",function(b){return rga(a,b)}),this.g=setInterval(function(){return Vu(a)},12E4),Vu(this))};Uu.prototype.stop=function(){null!=this.g&&(mb(this.s,"Stopping Wifi Status Monitoring."),clearInterval(this.g),this.g=null,Au(this.j,"STATUS_RESPONSE"))};
var rga=function(a,b){if(null!=a.g)if(b.status){var c={};null!=b.status.g&&(c.wifiSnr=b.status.g);null!=b.status.h&&(c.wifiSpeed=b.status.h[3]);0==Object.keys(c).length?a.s.L(function(){return"No status fields populated in response: "+JSON.stringify(b)}):(c.timestamp=Date.now(),30==a.h.length&&a.h.shift(),a.h.push(c),a.s.info(function(){return"Current Wifi status: "+JSON.stringify(c)}))}else a.s.L(function(){return"Ignoring response without status: "+JSON.stringify(b)})},Vu=function(a){a.j.sendMessage({type:"GET_STATUS",
sessionId:a.m,seqNum:km(a.l),get_status:["wifiSnr","wifiSpeed"]})};var Wu=function(a,b,c,d){this.H=b.Pg;this.o={extVersion:chrome.runtime.getManifest().version,extChannel:"public",mirrorSettings:Ri(a),sender:navigator.userAgent||"UNKNOWN",receiverProductName:b.Ie};this.J=c;this.G=d;this.l=this.h=this.u=this.D=this.m=this.F=this.j=null;this.g=[]};Wu.prototype.kh=function(a){null!=this.h&&clearInterval(this.h);this.j=a;this.F=Date.now();this.h=setInterval(this.C.bind(this,a),9E5)};
Wu.prototype.bi=function(){null!=this.h&&(clearInterval(this.h),this.h=null);if(null!=this.j){var a=this.C(this.j);this.j=null;return a}return Promise.resolve()};Wu.prototype.Kf=function(a,b){null==this.m&&(this.m=Date.now(),"function"===typeof a?this.D=a():"string"===typeof a&&(this.D=a),b&&"string"===typeof b.stack&&(this.u=b.stack))};
var sga=function(a,b){return(null==a.j?Promise.resolve():a.C(a.j)).then(function(){var c=b.map(function(d){d=Xu(a,d);var e=d.map(function(g){return g.events}).filter(function(g){return null!=g}),f=["["];d.map(function(g){return g.Rg}).forEach(function(g,k){0<k&&f.push(",");f.push(g)});f.push("]");return{events:new Blob(e,{type:"application/gzip"}),Rg:new Blob(f,{type:"application/json"})}});a.g=[];return c})};
Wu.prototype.C=function(a){var b=this;if(null!=this.l)return this.l;var c=wf(this.H).then(function(d){d={receiverVersion:d.g,receiverConnected:d.l,receiverOnEthernet:d.h,receiverHasUpdatePending:d.j,receiverUptimeSeconds:d.m};Object.assign(d,b.o);var e=Date.now();Object.assign(d,{startTime:b.F,endTime:e,activity:Lu(a),receiverWifiStatus:Array.from(b.G.h)});b.F=e;null!=b.m&&(Object.assign(d,{streamingErrorTime:b.m,streamingErrorMessage:b.D,streamingErrorCause:b.u}),b.m=null,b.D=null,b.u=null);return d});
return(this.l=Promise.all([c.then(function(d){return ega(a,d)}),c,fga(a)]).then(function(d){var e=l(d);d=e.next().value;var f=e.next().value;e=e.next().value;b.g.push({events:d,Rg:new Blob([JSON.stringify(Object.assign({tags:f},e))],{type:"application/json"})});b.g=Xu(b,b.J);b.l=null}))||Promise.resolve()};
var Xu=function(a,b){b-=2;for(var c=[],d=a.g.length-1;0<=d;--d){b-=a.g[d].Rg.size+1;if(0>b)break;c.push({events:null,Rg:a.g[d].Rg});if(null!=a.g[d].events){var e=a.g[d].events.size;b>=e&&(c[c.length-1].events=a.g[d].events,b-=e)}}return c.reverse()};var Yu=fb("mr.NetworkUtils"),Zu=function(a,b){if(!Eaa)return Promise.reject("TDLS feature not enabled.");Yu.info("setTDLSState_: ip="+a+", state="+b);return new Promise(function(c,d){chrome.networkingPrivate.setWifiTDLSEnabledState(a,b,function(e){chrome.runtime.lastError?(Yu.L("Unable to set TDLS state: state = "+b+", error = "+chrome.runtime.lastError.message),d("Unable to set TDLS state to "+b+".")):(Yu.info("TDLS state changed: state = "+b+", status = "+e),c(e))})})};var $u=function(a,b,c,d){d=void 0===d?null:d;Oi.call(this,b);var e=b.Gb;this.G=e.sessionId;this.M=e.Pg;this.C=a;this.O=d;this.s=fb("mr.mirror.cast.Session");this.F=new Cu;this.u=new jm("mirror.cast.SeqNumGenerator");this.o=new zu(b.id);this.D=new Tu(e,this.C,this.u,this.o,this.O);this.m=null;this.g=new Wu(a,e,c,new Uu(this.G,this.u,this.o));this.l=!1;this.J=null};q($u,Oi);h=$u.prototype;
h.start=function(a){var b=this;return Eu(this.F,1,function(c){var d=lu();return tga(b).then(function(e){b.l=e;return b.D.start(a,b)}).then(function(){if(b.D.j.G){var e=b.g;e.o.tdlsIsOn=b.l;e.G.start();uga(b)}else b.g.o.tdlsIsOn=b.l;d.end();b.J=mu();Gu(c,2);return b})})};
h.stop=function(){var a=this;return Fu(this.F,function(b){a.J&&(a.J.end(),a.J=null);a.g.G.stop();return a.D.stop().then(function(){return a.m?Ou(a.m):Promise.resolve()}).then(function(){a.m=null;return a.l?vga(a):Promise.resolve()}).then(function(){a.l=!1;Gu(b,4)})})};
h.qp=function(){var a=this,b={sessionId:this.G,seqNum:km(this.u),type:"PRESENTATION",icons:[],title:Qaa(this.Lc)};this.s.info("Sending session metadata update to receiver: "+this.G);this.o.sendMessage(b).catch(function(c){a.s.L("Failed to send activity to sink: "+c.message)})};h.kh=function(a){this.g.kh(a)};h.bi=function(){return this.g.bi()};h.Kf=function(a,b){this.g.Kf(a,b);this.s.error(a,b);this.stop()};
var av=function(a,b){return sga(a.g,b)},tga=function(a){a.s.info("maybeEnableTdls_: useTdls = "+a.C.useTdls);return a.C.useTdls?Zu(a.M,!0).then(function(b){if("Connected"==b)return a.s.info("Successfully enabled TDLS."),!0;a.s.L("Did not enable TDLS: result="+b);return!1}).catch(function(b){a.s.L("Error while calling enableTDLS()",b);return!1}):Promise.resolve(!1)},vga=function(a){return Zu(a.M,!1).catch(function(b){return a.s.error("Error while turning TDLS back off",b)})},uga=function(a){wga(a).then(function(b){(b.g||
[]).includes("video")?xga(a,b):a.s.L(function(){return"Receiver incapable of Media Remoting: "+JSON.stringify(b)})}).catch(function(b){a.s.L("None/Invalid capabilites response. Media Remoting disabled.",b)})},wga=function(a){return new Promise(function(b,c){var d={type:"GET_CAPABILITIES",sessionId:a.G,seqNum:km(a.u)};a.s.info(function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});Bu(a.o,d,"CAPABILITIES_RESPONSE",3E4,function(e,f){if(null==e)return c(f),!0;if("ok"!=e.result||!e.capabilities)return c(Error("Bad response: "+
JSON.stringify(e))),!0;if(e.h!=d.seqNum)return a.s.info(function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+JSON.stringify(e)}),!1;mb(a.s,function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});b(e.capabilities);return!0})})},xga=function(a,b){Eu(a.F,2,function(c){var d=a.h.Gb.Ie||"<UNKNOWN>";if(!d.startsWith("Chromecast")&&!d.startsWith("Eureka Dongle"))return a.s.L('HACK: Media Remoting disabled because the receiver model--"'+(d+'" according to discovery--is not a Chromecast.')),
Gu(c),Promise.resolve();a.m=new Nu(a.h,b,a.C,a.u,a.o,a.O);return a.m.initialize(a.W.bind(a),a).catch(function(e){a.s.error("Media Remoting start failed: "+e.message,e)}).then(function(){return Gu(c)})})};$u.prototype.W=function(){var a=this;return Eu(this.F,2,function(b){return new Promise(function(c,d){qga(a.D).then(function(){Gu(b,3);a.H=!0;Ji(a);c(a.Xa.bind(a))}).catch(function(e){a.Kf("Failed to suspend MediaStreamer before starting remoting",e);d(e)})})})};
$u.prototype.Xa=function(){var a=this;return Eu(this.F,3,function(b){return new Promise(function(c,d){a.D.resume().then(function(){Gu(b,2);a.H=!1;Ji(a);c()}).catch(function(e){a.Kf("Failed resume MediaStreamer after ending remoting mode",e);d(e)})})})};var bv=function(){Hi.call(this,"cast_streaming");this.D=this.F=this.H=this.J=this.l=null;this.aa=this.K="";this.ga=this.u=!1;this.kc=this.xa.bind(this);this.M=this.O=this.W=this.Xa=this.m=null};q(bv,Hi);h=bv.prototype;h.lh=function(a){this.u=a||!1;this.ga=!0};h.getName=function(){return"cast_streaming"};
h.Vk=function(a,b,c,d,e){var f=this;if(!this.u)return Hi.prototype.Vk.call(this,a,b,c,d,e);this.V.info("Start mirroring on route "+a.id);if(!this.ga)return di(Error("Not initialized"));var g=new Promise(function(k,m){f.o().then(function(){if(Di(b)&&c.shouldCaptureVideo)return ri(!1).then(function(p){f.aa=p})}).then(function(){return e?e(a).g:a}).then(function(p){f.K=b;yga(f,p);var u=f.J.createInterfacePtrAndBind(),A=f.H.createInterfacePtrAndBind(),E=zga(p,c);Aga(f,p,b,d);if(!f.l)throw new hi("Error to get mirroring service host");
f.F=new mojo.MirroringCastMessageChannelPtr;f.Xa=lu();f.l.start(E,u,A,mojo.makeRequest(f.F));f.m=new Oi(a,f.j.mk.bind(f.j));Ji(f.m);Bga(f,p,b);f.O=function(){return k(p)};f.M=m}).catch(function(p){f.V.info("Mirroring launch error: "+p);f.Kg(p.reason);m(p)})});return ei(g)};h.pi=function(a,b){return new $u(a,b,20969472,null)};h.Th=function(){nu(0)};h.Qh=function(){nu(1)};h.aj=function(){nu(2)};h.Rh=function(){zb("MediaRouter.CastStreaming.Session.End")};
h.Kg=function(a){Ab("MediaRouter.CastStreaming.Start.Failure",a,gi)};h.Sh=function(){zb("MediaRouter.CastStreaming.Stream.End")};
h.Fj=function(a){var b=this;return this.u?Promise.resolve():(new Promise(function(c){return chrome.metricsPrivate.getIsCrashReportingEnabled(c)})).then(function(c){var d=c&&Lfa(),e=[9351424];d&&e.push(20969472);return av(a,e).then(function(f){var g=f[f.length-1];f=vl(f[0].events).catch(function(k){b.V.error("Failed to persist events Blob.",k)});d&&0<g.events.size?qu(g.events,void 0,b.Ju.bind(b)):c&&pu("stats.json",g.Rg,void 0,void 0);return f})})};h.Ju=function(a){a&&(tu().g=Date.now())};
h.Uk=function(a){if(this.u)return cb();this.V.info("Received message to upload logs for "+a);return this.g?av(this.g,[20969472]).then(function(b){b=l(b).next().value;return 0==b.events.size?"":qu(b.events,a)}):Promise.resolve(Cga(this,a))};
var Cga=function(a,b){var c=window.localStorage.getItem("mr.temp.mirror.cast.Service.eventsBlob");if(null==c||1>c.length)c=null;else{for(var d=new Uint16Array(c.length),e=0;e<c.length;++e)d[e]=c.charCodeAt(e);c=d.buffer;d=(new Uint8Array(c,c.byteLength-1,1))[0];c=new Uint8Array(c,0,c.byteLength-(0==d?2:1));c=new Blob([c],{type:"application/gzip"})}if(null!=c&&0!=c.size)return vl(new Blob),a.V.info("Uploading saved logs for feedback."),qu(c,b)};h=bv.prototype;
h.onError=function(a){this.M&&(this.M(a),this.O=this.M=null,this.Kg(9));this.V.info("Mirroring service error: "+a);this.o()};h.didStart=function(){this.O&&(this.O(),this.O=this.M=null);this.Xa&&(this.Xa.end(),this.Xa=null);this.W=mu();Ci(this.K)?this.Th():Di(this.K)?this.Qh():Fi(this.K)&&this.aj()};h.didStop=function(){this.o()};h.send=function(a){if(this.D){var b=JSON.parse(a.jsonFormatData);mb(this.V,function(){return"Sending message: "+JSON.stringify(b)});this.D.sendMessage(a.jsonFormatData,{namespace:a.messageNamespace})}};
h.Ku=function(a){if(a&&(a.namespace_===mojo.MirroringWebRtcNamespace||a.namespace_===mojo.MirroringRemotingNamespace)&&this.F){var b=new mojo.MirroringCastMessage;b.messageNamespace=a.namespace_;"string"!==typeof a.data?this.V.info("Received non-string as JSON"):(b.jsonFormatData=a.data,this.F.send(b))}};
var yga=function(a,b){a.J=new mojo.Binding(mojo.MirroringSessionObserver,a,null);a.H=new mojo.Binding(mojo.MirroringCastMessageChannel,a,null);a.D=Et(b.id);a.D.onMessage=a.Ku.bind(a)},zga=function(a,b){var c=new mojo.MirroringSessionParameters;c.receiverAddress=new mojo.IPAddress;c.receiverAddress.addressBytes=a.Gb.Pg.split(".").map(function(d){return parseInt(d,10)});c.receiverModelName=a.Gb.Ie;c.type=b.shouldCaptureVideo&&b.shouldCaptureAudio?mojo.MirroringSessionType.AUDIO_AND_VIDEO:b.shouldCaptureVideo?
mojo.MirroringSessionType.VIDEO_ONLY:mojo.MirroringSessionType.AUDIO_ONLY;return c},Aga=function(a,b,c,d){a.l=new mojo.MirroringServiceHostPtr;b=b.Gb.tabId||-1;Ci(c)?a.j.getMirroringServiceHostForTab(b,mojo.makeRequest(a.l)):Di(c)?a.j.getMirroringServiceHostForDesktop(-1,a.aa,mojo.makeRequest(a.l)):Fi(c)?(b=new mojo.Url,b.url=c,a.j.getMirroringServiceHostForOffscreenTab(b,d||"",mojo.makeRequest(a.l))):a.l=null},Bga=function(a,b,c){Ci(c)&&!chrome.tabs.onUpdated.hasListener(a.kc)&&chrome.tabs.onUpdated.addListener(a.kc);
(Ci(c)||Fi(c))&&Li(a.m,b.Gb.tabId)};bv.prototype.xa=function(a,b,c){Bi(14);this.m&&Mi(this.m,a,b,c)};
bv.prototype.o=function(){chrome.tabs.onUpdated.removeListener(this.kc);return this.u?this.ga?this.l?(this.l.ptr.reset(),this.F=this.l=null,this.D&&this.D.jb(),this.D=null,this.J&&(this.J.close(),this.J=null),this.H&&(this.H.close(),this.H=null),this.j.Ui(this.m.h.id),this.m=null,this.aa=this.K="",this.W&&(this.W.end(),this.W=null),this.Rh(),Promise.resolve(!0)):Promise.resolve(!1):Promise.reject("Not initialized"):Hi.prototype.o.call(this)};
bv.prototype.Wk=function(a,b,c,d,e,f){return this.u?di(Error("Mirroring service does not support updating stream")):Hi.prototype.Wk.call(this,a,b,c,d,e,f)};bv.prototype.send=bv.prototype.send;bv.prototype.didStop=bv.prototype.didStop;bv.prototype.didStart=bv.prototype.didStart;bv.prototype.onError=bv.prototype.onError;var Dga=new bv;zi("mr.mirror.cast.Service",Dga);
